-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 03-07-2026 a las 02:38:16
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `horoscopobd`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pronostico_anual`
--

CREATE TABLE `pronostico_anual` (
  `id` int(11) NOT NULL,
  `signo` varchar(50) NOT NULL,
  `year2022` varchar(400) NOT NULL,
  `year2023` varchar(400) NOT NULL,
  `year2024` varchar(400) NOT NULL,
  `year2025` varchar(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `pronostico_anual`
--

INSERT INTO `pronostico_anual` (`id`, `signo`, `year2022`, `year2023`, `year2024`, `year2025`) VALUES
(1, 'aries', 'Amor: Tendrás épocas difíciles y épocas felices para este año, habrán sucesos que te pondrán aprueba.\r\nDinero: Toma siempre las mejores decisiones para que tú dinero alcance, y estés tranquilo en este sentido.\r\nSalud: Cuida de tu salud, solo tu decidirás si continuas así o mejorarás\r\n', 'Amor: Tus vínculos con tu círculo social mejorarán.\r\nDinero: La prosperidad llegará llegará tarde que temprano, aunque no la percibas\r\nSalud: Tu salud se verá reflejada en lo que haces, si cuidas tu salud verás los resultados\r\n', 'Amor: Verás realmente quien te aprecia y quién no\r\nDinero: Llegarán tiempos difíciles pero los superarás de la mejor manera.\r\nSalud: Te sentirás mejor cuando solo hagas por ti\r\n', 'Amor: Los vinculos con tu gente cercana se reforzarán aún más, además vendrá alguien especial a tu camino\r\nDinero: Tu situación laboral mejorará\r\nSalud: Deberás cuidar de tu salud precisamente en tiempos de arduo trabajo\r\n'),
(2, 'tauro', 'Amor: Para este año verás quienes de verdad te aprecian y de verdad no\r\nDinero: Solo con tus acciones te definirá la prosperidad\r\nSalud: Tu condición de salud solo la definirlas tu con tus acciones\r\n', 'Amor: Encontrarás a las personas que de verdad te estiman\r\nDinero: El trabajo llegará, se constante\r\nSalud: La salud para este año solo la definirlas tú.\r\n', 'Amor: Llegarán personas a tu vida que te producirán situaciones emocionales fuertes, ten cuidado\r\nDinero: La prosperidad llegará si dejas de tomar malas decisiones\r\nSalud: La salud para este año estará estable\r\n', 'Amor: Superarás un afecto emocional, sin embargo, no recaigas en esta situación que te herirá aún más\r\nDinero: Debes salir de situaciones financieras graves, trata de no pedir tantos préstamos\r\nSalud: Tu salud se verá afectada por tu situación emocional, trata de estar en paz.\r\n');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pronostico_diario`
--

CREATE TABLE `pronostico_diario` (
  `id` int(11) NOT NULL,
  `fecha` date DEFAULT NULL,
  `aries` varchar(200) DEFAULT NULL,
  `tauro` varchar(200) DEFAULT NULL,
  `geminis` varchar(200) DEFAULT NULL,
  `cancer` varchar(200) DEFAULT NULL,
  `leo` varchar(200) DEFAULT NULL,
  `virgo` varchar(200) DEFAULT NULL,
  `libra` varchar(200) DEFAULT NULL,
  `escorpion` varchar(200) DEFAULT NULL,
  `sagitario` varchar(200) DEFAULT NULL,
  `capricornio` varchar(200) DEFAULT NULL,
  `acuario` varchar(200) DEFAULT NULL,
  `piscis` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `pronostico_diario`
--

INSERT INTO `pronostico_diario` (`id`, `fecha`, `aries`, `tauro`, `geminis`, `cancer`, `leo`, `virgo`, `libra`, `escorpion`, `sagitario`, `capricornio`, `acuario`, `piscis`) VALUES
(1, '2022-03-25', 'Luchas contra la marea que tú mismo provocaste. No tienes que estar en pareja si no quieres. Un buen rato a solas te vendría bien. Arcano del día: el ermitaño.', 'No estás seguro de nada; sin embargo, sabes algunas verdades. Habla ahora antes de que esos secretos te perjudiquen. Arcano del día: los enamorados.', 'Mira hacia el frente. Tu energía a veces está tan desequilibrada que por eso no te sale nada de lo que quieres. Arcano del día: la muerte.', 'La noticia que estás esperando llegó. Acéptala con calma y mucho amor. La clave está en entender procesos de vida.', 'Así como le pones tanto empeño y pasión a tu relación de pareja, deberías hacer igual con tu familia y tu trabajo. Empieza a priorizar.', 'Suficiente con la presión que vives en tu trabajo y tu casa. Baja las revoluciones. Es mejor que vivas con más armonía, te vas a enfermar', 'Eres un ser brillante, con muchas habilidades. No te frustres porque no has encontrado tu verdadero centro. Debes calmarte.', 'Estás cambiando de ánimo al mismo tiempo que el reloj cambia de hora. Las emociones te llevan a toda velocidad.', 'Vas a encontrar a una persona muy generosa en tu camino. Aprovecha las estrellas que te envía el universo para mejorar.', 'Vas a tener que cambiar de tu actitud con tu familia. Es hora de dejar atrás los rencores y los malos días. La paz puede hacer parte de tus días.', 'Te sientes aburrido. No es la primera vez que te lo digo. La rutina te consume. Si no eres capaz de asumir nuevos retos, nada cambiará.\r\n\r\n', 'Hoy es el día para que digas: ¡no más! Todo está alineado para que tus decisiones se equilibren con tus deseos. Llénate de valor y fuerza.'),
(2, '2022-03-26', 'Las cosas prohibidas son las que más atraen, no solo en el plano emocional, también en el laboral. Mucho cuidado con los pasos en falso por favor.', 'Las personas nuevas que han llegado a tu vida serán tu mejor espejo. Toma lo positivo, pero especialmente no cambies tu forma de ser.', 'Apuesta siempre por las cosas por las que quieren que te reconozcan, sin miedo, y con mucha certeza. Necesitas un cambio urgente.', 'Estás demasiado sedentario, y por eso te sientes con la energía tan abajo. Tienes que empezar a moverte para reactivarte de una vez por todas.', 'Hoy tienes mucha lucidez mental, todas las decisiones que tomes serán las más acertadas para hacerle frente a lo que viene en camino.', 'Entre más alejes a la persona que quiere estar contigo, más la atraes. No pretendes escaparte del amor, es una emoción que debes vivir.', 'Querer hacer todo a la perfección te está llevando al límite. Tienes que entender que los errores hacen parte de la experiencia.', 'Este es el momento de pedir un aumento, o de recibirlo. Hace meses vienes con una luz ganadora que te permitirá evolucionar.', 'Deja esa costumbre de estarte retractando de las decisiones que tomas, te estás viendo seriamente afectado en este momento.', '¡Cuidado con las envidias! Lo mejor que puedes hacer ahora es ser discreto, guardar silencio y dejar que tu éxito pase desapercibido.', 'Te está costando mucho hacer cosas nuevas, pero tranquilo, siempre consigues lo que quieres. Solo es cuestión de organizarse.', 'Las injusticias te tienes aburrido. Tienes que salirte de ese círculo vicioso, tu trabajo no está aportando nada positivo a tus días.'),
(3, '2022-03-27', 'Este puede ser un domingo muy social, porque te vas a sentir más integrada o integrado a tu grupo de amigos, afianzar el lugar que ocupas en él, se vuelve muy importante.', 'Hoy puedes estar mucho más sensible a lo que la gente dice y piensa de ti. Tu reputación y tu imagen personal te interesan más que en otro momento del mes. Es un fin de semana para cuestionar el sitio', 'Hoy es un buen día para salir al mundo, hacer un viaje corto, pasear por una carretera larga y con muchas vistas panorámicas, salir a caminar o a recorrer la naturaleza. Es un buen fin de semana para ', 'El dinero de tu pareja o tu socio, puede ser un tema relevante a discutir o negociar el día de hoy, sobre todo si eres tú quien lo administra. Puedes recibir un bono, un préstamo o un regalo. Aprovech', 'Estás en sintonía con tus sentimientos, lo que te permitirá entender mejor la relación que tienes con tu pareja o socio, te es más claro lo que necesitas de ellos.', 'El enfoque del día de hoy te está pidiendo que revises si tus relaciones en el trabajo te satisfacen emocionalmente. Quizá estás desarrollándote en un ambiente demasiado hostil, pesado o estresante pa', 'Es un gran momento para el amor y el romance, vas a querer pasar tiempo de calidad con alguien especial para tu corazón. Es un día muy positivo para socializar, porque te sentirás bien al conectar con', 'Hoy puedes tener una actitud más reservada y silenciosa, necesitas tiempo para pasar dentro de tu propia mente. Usa esta energía para reflexionar y decidir qué es lo que quieres hacer, sin escuchar el', 'El día de hoy puedes comunicar tus emociones y necesidades más fácilmente, lo que te puede llevar a abrir el corazón con alguien que te permite hablar de lo que duele, de los procesos de duelo que tie', 'Cuidado con los excesos en los que puedas caer el día de hoy, ya que los tránsitos lunares parecen estarte invitando a darle rienda suelta a tus sentidos, especialmente a tu paladar. Aprovecha el día ', 'Puede que este no sea un momento en el que quieras quedarte callada o callado o esconder lo que sientes, porque tu estado de ánimo es impredecible y puedes estar un tanto voluble. Tómate tu tiempo par', 'Relájate, el día es para que te enfoques en ti y en tus necesidades emocionales. Agenda un día de descanso lejos del ruido del mundo y de las notificaciones en tu teléfono, es lo que ahora necesitas p'),
(4, '2022-03-28', 'Es un momento indicado para sentir equilibrio en tu interior y transmitirlo a los demás que te rodean.', 'Notarás que es un día para ocuparte de asuntos importantes relacionados con las herencias y las inversiones.', 'En este día podrás terminar una fase que dejarás atrás para comenzar algo distinto.', 'Es el momento adelantar tus actividades por la gran energía que fluye en tu vida.', 'Será un día en el cual es importante que colabores y seas cordial con las personas cercanas.', 'Estás en un día en el cual podrás solucionar asuntos pendientes y cerrar una etapa de tu vida. ', 'Es un momento para ocuparte de tu transformación personal y de ver la vida desde otro ángulo diferente.', 'Es un día para dejarte llevar por tus intuiciones y acertar de lleno en tus elecciones.', 'Es un día en el que deberás mantener el orden y la calma en tu entorno inmediato.', 'Estás en un día en el cual deberás aprender a perfeccionar tus talentos naturales', 'Podrás ocuparte de repartir cariño y diversión a los que te rodean. Tus asuntos se agilizarán.', 'Hoy podrás comenzar una nueva etapa y dinamizar tus acciones de una manera muy especial.'),
(5, '2022-03-29', 'Que buena época en la que estás entrando. Por fin la energía está transformada para hacer cambios laborales y emocionales. Adelante, sin miedo.', 'Ya estuviste alejado mucho tiempo de tu familia, no se trata solo de lo físico, también lo mental puede pesar en tus relaciones.', 'Si vas a confiar en tu intuición, no cambies de parecer cada segundo. Ejecuta lo que tienes en mente con certezas y menos dudas.', 'Tienes que parar, de verdad es desgastante que sigas enfrentado con las personas con las que tratas a diario. Deja los reproches a un lado.', 'Aprende a ver la parte positiva de las circunstancias que te rodean para que actúes y no te quedes en un drama eterno.', 'Tienes mucha ira guardada, esto puede hacer que explotes afectando tus relaciones. La grosería no te va a llevar a ninguna parte.', 'No tienes ni idea de qué es lo que está pasando con tu situación sentimental. Nada te sale, todo colapsa y tu cabeza no está tranquila nunca.', 'Este es el momento que estabas esperando en tu vida. Hay algunas cosas que ya no te interesan tanto y preferiste soltarlas para ser feliz.', 'No has logrado estabilizarte. Estás en un punto en el que no solucionas nada porque no hay claridad en lo que haces y lo que piensas.', 'Es posible que hoy te cuestiones todo el tiempo por lo que está pasando. No es normal que te castigues de la forma en que lo haces.', 'La ansiedad está causando estragos en tu familia. Tienes que alejarte un poco para que puedas encontrar las razones que te desequilibran tanto.', 'Tu ironía y agresividad harán que te hagas enemistades en los diferentes ámbitos en los que te mueves durante tu cotidianidad. ¡Cálmate!'),
(6, '2022-03-01', 'Hoy será un día ideal para iniciar nuevos proyectos. Confía en tus capacidades y evita tomar decisiones impulsivas en asuntos económicos.', 'La paciencia será tu mayor aliada. Una conversación pendiente podría traer tranquilidad y ayudarte a fortalecer una relación importante.', 'Recibirás noticias que despertarán tu curiosidad. Aprovecha las oportunidades para aprender algo nuevo y compartir tus ideas con quienes te rodean.', 'Dedica tiempo a tu bienestar emocional. Un gesto amable de alguien cercano te recordará el valor de las personas que siempre están a tu lado.', 'Tu entusiasmo llamará la atención de los demás. Mantén la humildad y trabaja en equipo para obtener mejores resultados en tus actividades.', 'La organización será clave para cumplir tus objetivos. No dejes que pequeñas preocupaciones te distraigan de lo verdaderamente importante.', 'Es un buen momento para buscar el equilibrio entre tus responsabilidades y el descanso. Tu creatividad será reconocida por quienes te rodean.', 'La determinación te permitirá superar un obstáculo inesperado. Escucha tu intuición antes de aceptar una propuesta importante.', 'El optimismo abrirá nuevas puertas en tu camino. Una oportunidad inesperada podría acercarte a una meta que habías dejado de lado.', 'El esfuerzo realizado durante los últimos días comenzará a dar frutos. Mantén la constancia y evita preocuparte por situaciones que no puedes controlar.', 'Tu originalidad será una ventaja para resolver un problema. Comparte tus ideas con confianza y mantente abierto a nuevas experiencias.', 'La sensibilidad te permitirá comprender mejor a quienes te rodean. Un momento de reflexión te ayudará a tomar una decisión con mayor seguridad.'),
(7, '2022-03-02', 'La energía que te acompaña hoy será suficiente para resolver asuntos pendientes. Evita discutir por temas sin importancia y enfócate en tus objetivos.', 'Un cambio inesperado en tu rutina traerá nuevas oportunidades. Mantén una actitud positiva y no temas salir de tu zona de confort.', 'Tu facilidad para comunicarte será clave para resolver un malentendido. Escucha con atención antes de sacar conclusiones apresuradas.', 'Las personas cercanas valorarán tu apoyo y comprensión. Es un buen día para fortalecer los lazos familiares y dejar atrás viejas diferencias.', 'Tu liderazgo será reconocido en el entorno laboral o académico. Aprovecha el momento para demostrar tu compromiso sin caer en el exceso de confianza.', 'No permitas que el perfeccionismo retrase tus planes. Avanzar paso a paso será más beneficioso que esperar el momento ideal.', 'Hoy encontrarás armonía al dedicar tiempo tanto a tus responsabilidades como a tus intereses personales. Un pequeño detalle alegrará tu jornada.', 'La perseverancia será tu mejor herramienta para superar un desafío. Confía en tu intuición y evita compartir tus planes con cualquiera.', 'El deseo de explorar nuevas ideas despertará tu entusiasmo. Una conversación interesante podría abrirte puertas que no habías considerado.', 'La disciplina que has mantenido comenzará a generar resultados favorables. Mantén la calma frente a los cambios y actúa con prudencia.', 'Tu creatividad destacará en un proyecto importante. No subestimes el valor de tus ideas, ya que podrían inspirar a quienes trabajan contigo.', 'Será un día propicio para reflexionar sobre tus metas personales. Escuchar a tu corazón te ayudará a encontrar la tranquilidad que estabas buscando.'),
(8, '2022-03-03', 'Las oportunidades llegarán cuando menos lo esperes. Mantén la confianza en ti mismo y no permitas que los comentarios negativos afecten tu ánimo.', 'Tu constancia comenzará a ser recompensada. Un asunto financiero podría tomar un rumbo favorable si actúas con prudencia.', 'La curiosidad te llevará a descubrir nuevas posibilidades. Aprovecha este día para aprender y compartir tus conocimientos con quienes te rodean.', 'Hoy será importante escuchar tus emociones antes de tomar una decisión. Un familiar o amigo cercano te brindará un consejo valioso.', 'Tu carisma abrirá puertas en el ámbito social. Es un buen momento para fortalecer relaciones y dejar una excelente impresión.', 'La planificación será tu mejor aliada para evitar contratiempos. No te exijas más de lo necesario y reconoce tus propios avances.', 'Encontrarás el equilibrio que estabas buscando al resolver un asunto pendiente. La paciencia será fundamental para mantener la armonía.', 'Tu intuición estará más fuerte de lo habitual. No ignores las señales que aparecen en tu camino y actúa con determinación.', 'El entusiasmo será contagioso y motivará a quienes trabajan contigo. Una nueva oportunidad podría acercarte a una meta importante.', 'La responsabilidad demostrada en los últimos días traerá reconocimiento. Continúa avanzando con disciplina y evita distraerte con asuntos secundarios.', 'Una idea innovadora despertará el interés de personas influyentes. Confía en tu creatividad y atrévete a expresar lo que piensas.', 'La tranquilidad llegará después de resolver una preocupación que ocupaba tu mente. Dedica un momento del día para agradecer lo bueno que tienes.'),
(9, '2022-03-04', 'Será un día favorable para cerrar ciclos y comenzar nuevas etapas. La confianza en tus decisiones marcará la diferencia en los resultados que obtengas.', 'La tranquilidad llegará a medida que resuelvas asuntos pendientes. No permitas que las preocupaciones del pasado afecten las oportunidades del presente.', 'Tu ingenio será de gran ayuda para resolver un problema inesperado. Mantén una actitud abierta y escucharás una propuesta que despertará tu interés.', 'La paciencia y la comprensión fortalecerán una relación importante. Dedica tiempo a quienes siempre han estado a tu lado y recibirás una grata recompensa.', 'Tu entusiasmo será contagioso y motivará a quienes te rodean. Es un excelente momento para asumir nuevos retos con determinación.', 'Los pequeños detalles harán una gran diferencia durante esta jornada. Organiza tus prioridades y evita dejar tareas importantes para después.', 'Una conversación sincera permitirá aclarar dudas y recuperar la armonía. Confía en tu capacidad para encontrar soluciones justas para todos.', 'Tu fortaleza interior te ayudará a superar cualquier obstáculo que aparezca. Evita actuar por impulso y analiza cada situación con calma.', 'Las buenas noticias podrían llegar a través de una persona cercana. Aprovecha cada oportunidad para ampliar tus conocimientos y experiencias.', 'La disciplina y el compromiso seguirán abriendo caminos hacia tus objetivos. Mantén el enfoque y no permitas que las distracciones retrasen tus planes.', 'Tu creatividad brillará en un proyecto que requiere ideas diferentes. Compartir tus pensamientos con los demás traerá resultados positivos.', 'Hoy sentirás la necesidad de hacer una pausa para reflexionar. Escuchar tu intuición será la mejor guía para tomar una decisión importante.'),
(10, '2022-03-05', 'Una decisión que has venido aplazando deberá tomarse pronto. Confía en tu experiencia y no permitas que el miedo limite tus posibilidades.', 'La estabilidad que buscas está más cerca de lo que imaginas. Mantén una actitud paciente y evita realizar gastos innecesarios durante el día.', 'Tu habilidad para adaptarte a los cambios será una gran ventaja. Una conversación inesperada podría abrir nuevas oportunidades para tu crecimiento.', 'El apoyo de una persona cercana será fundamental para recuperar la tranquilidad. No tengas miedo de expresar lo que realmente sientes.', 'Hoy destacarás por tu entusiasmo y capacidad para inspirar a los demás. Aprovecha este impulso para avanzar en un proyecto importante.', 'La organización y la disciplina te permitirán resolver asuntos pendientes con mayor facilidad. Recuerda que cada esfuerzo tiene su recompensa.', 'Buscar el equilibrio entre tus responsabilidades y tu vida personal te ayudará a sentirte más tranquilo. Un gesto de gratitud mejorará tu estado de ánimo.', 'Tu intuición será una guía confiable frente a una situación que parecía complicada. Mantén la calma y evita reaccionar impulsivamente.', 'La curiosidad te llevará a descubrir una oportunidad que podría beneficiarte en el futuro. Atrévete a explorar caminos diferentes.', 'El trabajo constante comenzará a reflejarse en resultados positivos. Sigue avanzando con determinación y no permitas que las dudas te detengan.', 'Una idea diferente despertará el interés de quienes comparten tus objetivos. Confía en tu creatividad y expresa tus opiniones con seguridad.', 'Será un día propicio para dejar atrás preocupaciones y mirar el futuro con optimismo. Escuchar tu voz interior te ayudará a encontrar la respuesta que buscas.'),
(11, '2022-03-06', 'Hoy descubrirás que la perseverancia comienza a dar resultados. Mantén una actitud positiva y no permitas que los pequeños obstáculos cambien tus planes.', 'Será un buen momento para fortalecer tus relaciones personales. La sinceridad abrirá puertas que parecían cerradas y traerá tranquilidad a tu día.', 'Las ideas surgirán con facilidad y encontrarás soluciones donde antes solo veías dificultades. Aprovecha este impulso para avanzar en tus proyectos.', 'Tu sensibilidad será una fortaleza para comprender a quienes te rodean. Un encuentro inesperado traerá una grata sorpresa que mejorará tu estado de ánimo.', 'La confianza en ti mismo te permitirá asumir nuevos retos con éxito. Escucha los consejos de alguien con experiencia antes de tomar una decisión importante.', 'El orden y la paciencia serán fundamentales para alcanzar tus objetivos. No intentes resolver todo al mismo tiempo; cada paso contará a tu favor.', 'La armonía llegará cuando dejes atrás viejas preocupaciones. Es un excelente día para dedicar tiempo a tus seres queridos y fortalecer los vínculos afectivos.', 'Tu intuición te ayudará a identificar una oportunidad que otros pasarán por alto. Actúa con prudencia y evita revelar todos tus planes.', 'La aventura llamará a tu puerta de una forma inesperada. Mantén la mente abierta, ya que una nueva experiencia podría dejar una enseñanza valiosa.', 'Los esfuerzos realizados en silencio comenzarán a ser reconocidos. Continúa trabajando con disciplina y verás cómo las recompensas llegan poco a poco.', 'Una propuesta interesante despertará tu entusiasmo. Confía en tus capacidades y atrévete a compartir tus ideas sin temor a las críticas.', 'Encontrarás paz al dedicar unos minutos para reflexionar sobre tus metas. La paciencia y la esperanza serán tus mejores aliadas durante esta jornada.'),
(12, '2022-03-07', 'La energía de este día te impulsará a tomar decisiones importantes. Confía en tus capacidades y evita actuar con demasiada prisa.', 'Un asunto pendiente comenzará a resolverse de manera favorable. Mantén la calma y no permitas que las dudas afecten tu confianza.', 'Tu capacidad de adaptación será clave para enfrentar los cambios. Una conversación interesante podría abrirte nuevas oportunidades.', 'La cercanía de una persona especial te brindará tranquilidad. Es un buen momento para expresar tus sentimientos con sinceridad.', 'Tu entusiasmo contagiará a quienes te rodean y facilitará el trabajo en equipo. Aprovecha esta buena racha para avanzar en tus metas.', 'La organización te ayudará a resolver tareas acumuladas. No subestimes el valor de los pequeños progresos que has logrado recientemente.', 'Buscar el equilibrio entre tus responsabilidades y el descanso será fundamental. Una noticia positiva mejorará tu estado de ánimo.', 'Tu intuición te permitirá identificar una situación que requiere atención. Actúa con prudencia y evita tomar decisiones impulsivas.', 'El deseo de explorar nuevas posibilidades despertará tu motivación. Mantén la mente abierta y aprovecha cada aprendizaje del día.', 'La disciplina y la constancia comenzarán a generar resultados visibles. Sigue avanzando con paciencia y confianza en el proceso.', 'Tu creatividad destacará en un proyecto importante. Compartir tus ideas con otros podría traer beneficios inesperados.', 'Será una jornada favorable para reflexionar sobre tus prioridades. Escuchar tu voz interior te ayudará a encontrar claridad y serenidad.'),
(13, '2022-03-08', 'Este día será propicio para dejar atrás las dudas y enfocarte en tus metas. La determinación que demuestres hoy marcará la diferencia en tus resultados.', 'La paciencia te permitirá resolver una situación que parecía complicada. Confía en el proceso y evita preocuparte por aquello que no puedes controlar.', 'Una oportunidad inesperada pondrá a prueba tu creatividad. No tengas miedo de expresar tus ideas, ya que serán bien recibidas por quienes te rodean.', 'Encontrarás tranquilidad al compartir tiempo con las personas que aprecias. Un consejo sincero llegará en el momento justo para ayudarte a tomar una decisión.', 'Tu liderazgo será reconocido y podrás inspirar a otros con tu entusiasmo. Aprovecha este impulso para avanzar en los proyectos que has pospuesto.', 'La disciplina y el orden serán tus mejores aliados durante la jornada. Resolverás un asunto pendiente con mayor facilidad de la que imaginabas.', 'La armonía llegará cuando decidas escuchar diferentes puntos de vista. Mantén una actitud abierta y descubrirás nuevas oportunidades para crecer.', 'Tu intuición será especialmente acertada en asuntos importantes. Evita actuar por impulso y analiza con calma cada alternativa antes de decidir.', 'El optimismo abrirá puertas que parecían cerradas. Un nuevo reto despertará tu interés y te permitirá demostrar todo tu potencial.', 'Los esfuerzos realizados durante las últimas semanas comenzarán a ser recompensados. Sigue trabajando con constancia y no pierdas de vista tus objetivos.', 'Una idea innovadora podría convertirse en el inicio de un gran proyecto. Confía en tus capacidades y atrévete a dar el primer paso.', 'Será un día ideal para reflexionar sobre lo que realmente deseas para el futuro. La serenidad y la confianza te ayudarán a encontrar el camino correcto.'),
(14, '2022-03-09', 'Hoy será un excelente momento para confiar en tu intuición. Una decisión tomada con seguridad podría abrirte el camino hacia nuevas oportunidades.', 'La perseverancia dará frutos más pronto de lo que imaginas. Evita apresurarte y permite que cada situación siga su curso natural.', 'Una noticia inesperada despertará tu entusiasmo. Aprovecha este impulso para retomar un proyecto que habías dejado en pausa.', 'La tranquilidad llegará cuando dejes de cargar preocupaciones ajenas. Dedica tiempo a tu bienestar y fortalece los vínculos con quienes más aprecias.', 'Tu actitud positiva será clave para superar cualquier dificultad. Mantén la confianza y demuestra de lo que eres capaz sin buscar la aprobación de los demás.', 'Será un día favorable para organizar tus ideas y establecer nuevas prioridades. Los pequeños cambios de hoy traerán grandes beneficios en el futuro.', 'La comunicación será tu mejor herramienta para resolver diferencias. Escuchar con atención permitirá fortalecer relaciones importantes.', 'Tu determinación te ayudará a enfrentar un desafío con éxito. No reveles todos tus planes; algunas metas avanzan mejor con discreción.', 'La curiosidad te llevará a descubrir una oportunidad interesante. Mantén una mente abierta y no descartes propuestas fuera de lo habitual.', 'El compromiso y la disciplina seguirán acercándote a tus objetivos. Confía en el trabajo realizado y no permitas que la impaciencia te desanime.', 'Una idea diferente llamará la atención de personas importantes. Aprovecha el momento para compartir tus conocimientos y aprender de nuevas experiencias.', 'La calma será tu mejor aliada durante esta jornada. Escuchar a tu corazón te permitirá tomar una decisión que traerá paz y satisfacción.'),
(15, '2022-03-10', 'Las circunstancias estarán a tu favor para resolver un asunto que llevaba tiempo preocupándote. Confía en tu criterio y actúa con determinación.', 'La paciencia y la constancia serán recompensadas. Hoy descubrirás que los pequeños esfuerzos también conducen a grandes resultados.', 'Una conversación inesperada despertará nuevas ideas. Aprovecha la oportunidad para ampliar tus conocimientos y fortalecer tus relaciones.', 'Tu intuición será una gran guía durante este día. Escucha con atención a las personas que te aprecian, pues una de ellas tendrá un consejo valioso.', 'El entusiasmo con el que afrontes tus responsabilidades será reconocido. No dejes que los comentarios negativos desvíen tu atención de tus metas.', 'La organización será fundamental para mantener el equilibrio. Resolverás una tarea pendiente con mayor facilidad de la que imaginabas.', 'Será una jornada propicia para recuperar la armonía en tus relaciones. Un gesto de amabilidad hará que alguien valore aún más tu compañía.', 'Tu fortaleza interior te permitirá afrontar un reto importante. Mantén la calma y analiza cada situación antes de tomar una decisión definitiva.', 'La buena actitud abrirá puertas que parecían cerradas. Una oportunidad relacionada con tus proyectos personales podría sorprenderte gratamente.', 'El compromiso que has demostrado comenzará a dar frutos. Continúa trabajando con disciplina y no permitas que la impaciencia te haga dudar.', 'Tu creatividad destacará en una actividad que requiere soluciones diferentes. Comparte tus ideas con confianza y escucharás opiniones favorables.', 'Encontrarás tranquilidad al dedicar tiempo para reflexionar sobre tus prioridades. Hoy comprenderás que cada experiencia tiene un propósito para tu crecimiento.'),
(16, '2022-03-11', 'Hoy será un buen momento para tomar la iniciativa en asuntos importantes. La confianza en tus capacidades te permitirá superar cualquier obstáculo que se presente.', 'Una oportunidad inesperada llegará cuando menos lo imagines. Mantén la calma y analiza cada detalle antes de comprometerte con una nueva responsabilidad.', 'Tu habilidad para comunicarte será clave para resolver una situación pendiente. Escuchar con atención te ayudará a evitar malentendidos.', 'Las emociones estarán más equilibradas y encontrarás respuestas que llevabas tiempo buscando. Disfruta de la compañía de quienes te brindan tranquilidad.', 'Tu entusiasmo será reconocido por las personas que trabajan contigo. Aprovecha esta energía para avanzar en proyectos que requieren dedicación.', 'La paciencia y la disciplina te permitirán alcanzar un objetivo importante. No permitas que las pequeñas dificultades afecten tu motivación.', 'Será una jornada ideal para fortalecer amistades y aclarar diferencias. Un gesto de generosidad traerá armonía a tu entorno.', 'Tu intuición estará especialmente desarrollada. Confía en tus corazonadas y evita tomar decisiones apresuradas por influencia de terceros.', 'El deseo de aprender algo nuevo despertará tu interés por explorar diferentes caminos. Una experiencia inesperada dejará una valiosa enseñanza.', 'Los esfuerzos que has realizado en silencio comenzarán a ser valorados. Continúa avanzando con responsabilidad y mantén la vista en tus metas.', 'Tu creatividad te permitirá encontrar soluciones donde otros solo ven problemas. Comparte tus ideas con seguridad y acepta nuevas perspectivas.', 'La serenidad será tu mejor compañera durante este día. Dedicar unos minutos a la reflexión te ayudará a tomar una decisión acertada para tu futuro.'),
(17, '2022-03-12', 'Hoy será un día para confiar en tu intuición y avanzar con determinación. Una oportunidad inesperada podría acercarte a una de tus metas más importantes.', 'La tranquilidad regresará a tu vida si dejas atrás las preocupaciones innecesarias. Mantén la paciencia y verás cómo las cosas comienzan a mejorar.', 'Tu facilidad para adaptarte a los cambios será una gran ventaja. Una conversación interesante podría abrirte nuevas puertas en el ámbito personal o laboral.', 'Es un buen momento para fortalecer los vínculos con quienes aprecias. Un gesto de cariño será suficiente para mejorar el ambiente a tu alrededor.', 'Tu entusiasmo será contagioso y despertará la admiración de quienes te rodean. Aprovecha esta energía para iniciar aquello que has estado posponiendo.', 'La organización y la disciplina te ayudarán a superar los retos del día. No te desanimes si los resultados tardan un poco más de lo esperado.', 'La armonía llegará cuando escuches con atención las opiniones de los demás. Una actitud conciliadora traerá beneficios para todos.', 'Tu determinación será puesta a prueba, pero saldrás fortalecido de cualquier desafío. Mantén la calma y actúa con inteligencia antes de decidir.', 'Las buenas noticias podrían llegar por medio de una persona cercana. Mantén el optimismo y no dudes en aprovechar las oportunidades que aparezcan.', 'El esfuerzo constante comenzará a reflejarse en logros importantes. Sigue trabajando con responsabilidad y no pierdas de vista tus objetivos.', 'Una idea innovadora despertará el interés de quienes comparten tus proyectos. Confía en tu creatividad y atrévete a proponer soluciones diferentes.', 'La paz interior será la clave para afrontar cualquier situación. Dedica un momento del día para reflexionar y agradecer por los avances que has conseguido.'),
(18, '2022-03-13', 'Hoy será un día favorable para tomar decisiones con seguridad. Confía en tu experiencia y no permitas que las dudas retrasen tus proyectos.', 'La paciencia seguirá siendo tu mejor aliada. Un esfuerzo realizado hace algún tiempo comenzará a dar resultados positivos.', 'Una nueva oportunidad despertará tu curiosidad y te motivará a salir de la rutina. Mantén una actitud abierta ante los cambios.', 'Las personas que te rodean valorarán tu apoyo y comprensión. Dedicar tiempo a la familia traerá tranquilidad y momentos agradables.', 'Tu energía será suficiente para afrontar cualquier desafío. Aprovecha el día para avanzar en aquello que has estado dejando para después.', 'La organización marcará la diferencia en tus actividades. Evita preocuparte por detalles sin importancia y concéntrate en lo esencial.', 'Encontrarás soluciones gracias a tu capacidad para escuchar diferentes puntos de vista. La armonía volverá a un asunto que parecía complicado.', 'Tu intuición te permitirá descubrir una oportunidad que otros no verán. Actúa con prudencia y mantén en reserva algunos de tus planes.', 'El entusiasmo será el motor que impulse tus objetivos. Una experiencia inesperada dejará una enseñanza valiosa para tu futuro.', 'La responsabilidad con la que has actuado será reconocida por personas importantes. Continúa trabajando con disciplina y confianza.', 'Tu creatividad brillará en un momento clave. No tengas miedo de compartir tus ideas, ya que recibirán una respuesta positiva.', 'Será una jornada ideal para reflexionar sobre tus metas y renovar tus esperanzas. La calma interior te ayudará a tomar la mejor decisión.'),
(19, '2022-03-14', 'La confianza en tus capacidades te permitirá superar un desafío que parecía complicado. Hoy descubrirás que cada esfuerzo realizado comienza a dar sus frutos.', 'Será un día favorable para fortalecer tus proyectos personales. Mantén la calma frente a los cambios y evita tomar decisiones apresuradas.', 'Tu habilidad para comunicarte abrirá nuevas oportunidades. Una conversación casual podría convertirse en el inicio de una experiencia muy positiva.', 'Las emociones estarán más estables y encontrarás apoyo en alguien de confianza. Aprovecha el día para compartir tiempo con las personas que aprecias.', 'Tu entusiasmo será reconocido por quienes te rodean. Es un excelente momento para asumir nuevas responsabilidades con optimismo y determinación.', 'La disciplina y el orden te ayudarán a resolver asuntos pendientes. No permitas que pequeños contratiempos desvíen tu atención de lo realmente importante.', 'La armonía llegará cuando decidas escuchar antes de juzgar. Un gesto de comprensión fortalecerá una relación que consideras valiosa.', 'Tu intuición estará especialmente acertada durante esta jornada. Analiza cada oportunidad con calma y actúa solo cuando estés completamente seguro.', 'El deseo de avanzar te llevará a descubrir caminos diferentes. No tengas miedo de aceptar nuevos retos, pues traerán valiosas enseñanzas.', 'Los resultados de tu dedicación comenzarán a hacerse evidentes. Continúa trabajando con responsabilidad y evita preocuparte por aquello que escapa de tu control.', 'Una idea innovadora despertará el interés de personas importantes. Confía en tu creatividad y aprovecha el momento para demostrar tu talento.', 'La tranquilidad llegará cuando decidas dejar atrás pensamientos negativos. Hoy será un buen día para reflexionar sobre tus sueños y renovar tus energías.'),
(20, '2022-03-15', 'Una oportunidad que no esperabas podría presentarse hoy. Mantén una actitud positiva y confía en tus capacidades para aprovechar cada momento.', 'La paciencia será recompensada con una noticia favorable. Evita preocuparte por situaciones que aún no han ocurrido y disfruta del presente.', 'Tu facilidad para encontrar soluciones te permitirá resolver un inconveniente con rapidez. Escucha nuevas ideas antes de tomar una decisión importante.', 'Será un día ideal para fortalecer los lazos con quienes más aprecias. Una conversación sincera traerá tranquilidad y mayor comprensión.', 'Tu entusiasmo y determinación llamarán la atención de personas importantes. Aprovecha esta energía para avanzar en tus proyectos personales.', 'La organización será la clave para cumplir con todas tus responsabilidades. No permitas que los pequeños detalles te hagan perder el enfoque.', 'Encontrarás el equilibrio que tanto buscabas al actuar con serenidad. Un gesto amable mejorará una relación que parecía distante.', 'La intuición te ayudará a tomar una decisión acertada. Mantén la discreción con tus planes y deja que los resultados hablen por sí solos.', 'El optimismo te impulsará a aceptar nuevos desafíos. Una experiencia diferente ampliará tu visión y fortalecerá tu confianza.', 'La constancia demostrada durante las últimas semanas comenzará a reflejarse en resultados positivos. Sigue adelante sin perder la disciplina.', 'Tu creatividad será una herramienta valiosa para superar un reto inesperado. Compartir tus ideas con otras personas abrirá nuevas posibilidades.', 'La calma interior te permitirá ver con claridad el camino a seguir. Dedica unos minutos a reflexionar y descubrirás respuestas que antes no veías.'),
(21, '2022-03-16', 'Hoy será un buen momento para dejar atrás las dudas y actuar con decisión. La confianza en ti mismo te permitirá superar cualquier desafío que aparezca.', 'La tranquilidad llegará gracias a una decisión acertada. Mantén la paciencia y verás cómo las circunstancias comienzan a favorecerte.', 'Una conversación inesperada despertará nuevas oportunidades. Aprovecha tu facilidad para comunicarte y expresar aquello que has estado guardando.', 'Las emociones estarán más equilibradas durante esta jornada. Disfruta de los pequeños momentos junto a quienes ocupan un lugar especial en tu vida.', 'Tu actitud positiva inspirará a las personas que te rodean. Es un excelente día para iniciar proyectos o retomar aquellos que habías dejado en pausa.', 'La disciplina y la organización serán fundamentales para alcanzar tus objetivos. Evita distraerte con asuntos que no aportan a tu crecimiento.', 'Encontrarás la armonía al resolver un malentendido con serenidad. Escuchar antes de responder será la mejor decisión durante este día.', 'Tu intuición estará especialmente desarrollada y te ayudará a identificar una oportunidad importante. Actúa con prudencia y mantén la confianza en tus decisiones.', 'El entusiasmo con el que afrontes los cambios abrirá nuevas puertas. No tengas miedo de explorar caminos diferentes y aprender de nuevas experiencias.', 'El esfuerzo constante comenzará a reflejarse en resultados que te llenarán de satisfacción. Continúa avanzando con responsabilidad y determinación.', 'Una idea innovadora podría convertirse en el comienzo de un proyecto exitoso. Confía en tu creatividad y no temas compartir tus propuestas.', 'Será un día ideal para reflexionar sobre tus metas y renovar tus energías. La serenidad te permitirá encontrar respuestas donde antes solo había incertidumbre.'),
(22, '2022-03-17', 'La perseverancia será tu mayor fortaleza durante este día. No dejes que los pequeños inconvenientes te hagan perder de vista tus objetivos.', 'Una oportunidad para mejorar tu situación aparecerá cuando menos lo esperes. Mantén la confianza y actúa con serenidad antes de decidir.', 'Tu creatividad estará en uno de sus mejores momentos. Aprovecha este impulso para resolver asuntos pendientes y compartir tus ideas con los demás.', 'La tranquilidad llegará al dejar atrás preocupaciones que ya no tienen sentido. Rodéate de personas que transmitan confianza y optimismo.', 'Tu liderazgo será valorado por quienes trabajan o estudian contigo. Mantén una actitud humilde y los resultados serán aún más favorables.', 'Será una jornada ideal para organizar tus prioridades. Resolverás un asunto que llevaba tiempo ocupando tu atención si actúas con paciencia.', 'La armonía regresará a una relación importante gracias a una conversación sincera. Escuchar con empatía marcará la diferencia.', 'Tu intuición te permitirá descubrir una alternativa que otros no habían considerado. Confía en tus instintos, pero analiza cada paso con calma.', 'El entusiasmo con el que afrontes los retos abrirá nuevas posibilidades. Una experiencia inesperada podría convertirse en una gran oportunidad.', 'El compromiso que has demostrado empezará a ser reconocido. Continúa trabajando con disciplina y evita distraerte con asuntos poco importantes.', 'Una propuesta diferente despertará tu interés y estimulará tu imaginación. No tengas miedo de probar nuevos caminos para alcanzar tus metas.', 'Será un día propicio para recuperar el equilibrio emocional. Dedica un momento a reflexionar y encontrarás la claridad que necesitabas para seguir adelante.'),
(23, '2022-03-18', 'Hoy será un día favorable para demostrar todo tu potencial. Mantén la confianza en tus decisiones y no permitas que las dudas frenen tu progreso.', 'La calma y la paciencia serán fundamentales para resolver un asunto pendiente. Una buena noticia llegará cuando menos lo esperes.', 'Tu facilidad para adaptarte a los cambios te abrirá nuevas oportunidades. Escucha con atención las sugerencias de quienes desean verte crecer.', 'Una persona cercana te brindará el apoyo que necesitabas. Aprovecha este momento para fortalecer los lazos familiares y valorar los pequeños detalles.', 'Tu entusiasmo será la clave para alcanzar un objetivo importante. Mantén una actitud positiva y contagiarás tu energía a quienes te rodean.', 'La organización te permitirá cumplir con todas tus responsabilidades sin mayores contratiempos. No descuides los momentos de descanso.', 'La armonía llegará gracias a una conversación sincera. Actuar con comprensión te ayudará a resolver una diferencia que parecía difícil.', 'Tu intuición volverá a guiarte por el camino correcto. Analiza cada oportunidad con calma y evita tomar decisiones impulsivas.', 'El deseo de aprender y descubrir nuevas experiencias despertará grandes oportunidades. Atrévete a salir de la rutina y acepta nuevos desafíos.', 'La constancia con la que has trabajado comenzará a reflejarse en resultados positivos. Sigue adelante sin perder la disciplina que te caracteriza.', 'Una idea original llamará la atención de personas importantes. Confía en tu creatividad y no dudes en compartir tus proyectos.', 'Será una jornada ideal para encontrar paz interior y renovar tus esperanzas. Escuchar tu intuición te ayudará a tomar una decisión acertada.'),
(24, '2022-03-19', 'Hoy tendrás la oportunidad de demostrar tu capacidad para superar cualquier desafío. Confía en tus habilidades y mantén una actitud positiva frente a los cambios.', 'La paciencia seguirá siendo tu mejor aliada. Un asunto que parecía estancado comenzará a avanzar de manera favorable si actúas con serenidad.', 'Tu ingenio será de gran utilidad para resolver un inconveniente inesperado. Aprovecha este día para compartir tus ideas y aprender de nuevas experiencias.', 'Las personas que te rodean apreciarán tu comprensión y apoyo. Un momento especial con la familia o los amigos renovará tu ánimo.', 'Tu entusiasmo abrirá puertas que parecían cerradas. Es un excelente momento para asumir nuevos retos y demostrar todo tu potencial.', 'La organización y el compromiso te permitirán avanzar con mayor seguridad. No dejes que las preocupaciones menores desvíen tu atención de lo importante.', 'La armonía llegará cuando decidas actuar con paciencia y escuchar diferentes opiniones. Un pequeño gesto fortalecerá una relación valiosa.', 'Tu intuición será una guía confiable para tomar una decisión importante. Mantén la discreción y permite que los resultados hablen por sí solos.', 'Una oportunidad inesperada despertará tu deseo de explorar nuevos caminos. Aprovecha cada experiencia como una ocasión para crecer.', 'La disciplina y el esfuerzo constante comenzarán a generar el reconocimiento que esperabas. Continúa avanzando con confianza y determinación.', 'Tu creatividad destacará en una actividad que requiere soluciones innovadoras. No temas expresar tus ideas, ya que recibirán una respuesta positiva.', 'La tranquilidad que buscas llegará al dejar atrás pensamientos negativos. Dedica tiempo a reflexionar y descubrirás nuevas razones para mirar el futuro con optimismo.'),
(25, '2022-03-20', 'Hoy será un excelente día para tomar la iniciativa en asuntos importantes. Confía en tu intuición y no permitas que el temor limite tus posibilidades.', 'La estabilidad que tanto has buscado comenzará a hacerse presente. Mantén la paciencia y evita apresurarte en decisiones relacionadas con el dinero.', 'Una conversación inesperada despertará nuevas ideas y ampliará tu perspectiva. Aprovecha el momento para expresar tus opiniones con seguridad.', 'Las muestras de cariño de una persona cercana alegrarán tu jornada. Es un buen momento para fortalecer los lazos familiares y dejar atrás viejas diferencias.', 'Tu entusiasmo será la clave para superar cualquier desafío. No dudes en asumir nuevas responsabilidades, pues demostrarás de lo que eres capaz.', 'La organización y la constancia te permitirán cumplir con tus objetivos. Evita distraerte con asuntos que no aportan a tu crecimiento personal.', 'Encontrarás el equilibrio al actuar con serenidad frente a una situación inesperada. La diplomacia será tu mejor herramienta durante este día.', 'Tu intuición te llevará por el camino correcto. Analiza cada oportunidad con calma y evita revelar tus planes antes de tiempo.', 'El optimismo abrirá puertas hacia nuevas experiencias. Una propuesta interesante podría acercarte a una meta que considerabas lejana.', 'Los frutos de tu esfuerzo comenzarán a hacerse evidentes. Sigue trabajando con disciplina y no permitas que la impaciencia cambie tu rumbo.', 'Una idea original despertará la admiración de quienes te rodean. Confía en tu creatividad y aprovecha la oportunidad para innovar.', 'La paz interior llegará cuando decidas dejar atrás preocupaciones innecesarias. Dedica un momento del día a reflexionar sobre todo lo bueno que has conseguido.'),
(26, '2022-03-21', 'La confianza que deposites en tus capacidades será la clave para alcanzar un objetivo importante. Aprovecha este día para avanzar con decisión y optimismo.', 'Un cambio inesperado traerá nuevas posibilidades para tu crecimiento. Mantén la calma y recuerda que la paciencia siempre ofrece buenos resultados.', 'Tu habilidad para comunicarte te permitirá resolver un asunto pendiente. Escuchar con atención será tan importante como expresar tus propias ideas.', 'Será una jornada ideal para fortalecer los vínculos con las personas que más aprecias. Un gesto sincero traerá tranquilidad y alegría a tu corazón.', 'La energía positiva que transmites inspirará a quienes te rodean. No dudes en asumir nuevos retos, pues demostrarás todo tu potencial.', 'La disciplina y el orden seguirán dando excelentes resultados. Organiza tus prioridades y evita dejar tareas importantes para el último momento.', 'La armonía regresará a una relación que había pasado por un momento difícil. La comprensión y el respeto marcarán la diferencia durante este día.', 'Tu intuición te ayudará a descubrir una oportunidad que parecía oculta. Analiza cada detalle antes de actuar y confía en tu experiencia.', 'Una nueva experiencia despertará tu entusiasmo y ampliará tu manera de ver las cosas. Mantén una actitud abierta frente a los cambios.', 'El esfuerzo constante comenzará a recibir el reconocimiento que merece. Continúa trabajando con responsabilidad y no pierdas la motivación.', 'Tu creatividad será una herramienta valiosa para resolver un desafío inesperado. Comparte tus ideas con confianza y acepta nuevas perspectivas.', 'Encontrarás la serenidad que estabas buscando al dedicar tiempo a tus verdaderos intereses. Una reflexión oportuna te ayudará a tomar una excelente decisión.'),
(27, '2022-03-22', 'Hoy será un día para confiar en tus decisiones y avanzar con determinación. Una oportunidad inesperada podría acercarte a una meta que dabas por lejana.', 'La paciencia te permitirá resolver un asunto importante sin mayores dificultades. Evita apresurarte y deja que las situaciones encuentren su propio ritmo.', 'Tu capacidad para adaptarte a los cambios será una gran ventaja. Una nueva propuesta despertará tu interés y abrirá posibilidades de crecimiento.', 'Las emociones estarán más equilibradas y encontrarás apoyo en quienes siempre han estado a tu lado. Aprovecha el día para fortalecer esos vínculos.', 'Tu liderazgo y entusiasmo serán reconocidos por quienes comparten tus responsabilidades. Mantén una actitud humilde y los resultados serán aún mejores.', 'La organización será la clave para cumplir con todo lo que tienes pendiente. No permitas que las pequeñas distracciones retrasen tus objetivos.', 'La armonía regresará a tu entorno gracias a una conversación sincera. Escuchar diferentes opiniones te ayudará a tomar una mejor decisión.', 'Tu intuición será una guía confiable frente a una situación inesperada. Actúa con prudencia y evita revelar tus planes antes de tiempo.', 'El optimismo con el que afrontes este día atraerá nuevas oportunidades. Una experiencia diferente dejará una enseñanza que te será útil en el futuro.', 'La disciplina y la constancia comenzarán a reflejarse en resultados favorables. Continúa avanzando con responsabilidad y confianza en tus capacidades.', 'Una idea innovadora llamará la atención de personas importantes. No dudes en compartir tus proyectos, pues recibirán una respuesta positiva.', 'La tranquilidad llegará cuando decidas enfocarte en lo realmente importante. Un momento de reflexión te permitirá ver con claridad el camino que debes seguir.'),
(28, '2022-03-23', 'Hoy será un buen momento para avanzar con determinación hacia tus objetivos. La confianza en ti mismo te permitirá superar cualquier dificultad que aparezca.', 'La paciencia y la constancia comenzarán a dar los resultados que esperabas. Evita preocuparte por situaciones que pronto encontrarán solución.', 'Tu capacidad para resolver problemas será admirada por quienes te rodean. Una conversación inesperada traerá una oportunidad interesante.', 'Las personas cercanas valorarán tu apoyo y comprensión. Dedicar tiempo a la familia o a los amigos fortalecerá lazos importantes.', 'Tu entusiasmo abrirá nuevas puertas en el ámbito personal o profesional. Aprovecha esta jornada para demostrar todo tu potencial.', 'La organización y el compromiso serán fundamentales para cumplir tus responsabilidades. No dejes que pequeños inconvenientes alteren tus planes.', 'Encontrarás armonía al actuar con paciencia y escuchar antes de responder. Un gesto de amabilidad mejorará una relación importante.', 'Tu intuición será una gran aliada para tomar decisiones acertadas. Analiza cada detalle antes de comprometerte con nuevos proyectos.', 'Una experiencia diferente despertará tu curiosidad y renovará tu motivación. Mantén una actitud positiva frente a los cambios que se presenten.', 'El esfuerzo realizado durante las últimas semanas comenzará a ser reconocido. Sigue trabajando con disciplina y mantén la vista en tus metas.', 'Tu creatividad destacará en un momento clave del día. Compartir tus ideas con otras personas traerá beneficios que no esperabas.', 'Será una jornada propicia para reflexionar sobre tus sueños y prioridades. La tranquilidad que encuentres hoy te ayudará a tomar mejores decisiones en el futuro.');
INSERT INTO `pronostico_diario` (`id`, `fecha`, `aries`, `tauro`, `geminis`, `cancer`, `leo`, `virgo`, `libra`, `escorpion`, `sagitario`, `capricornio`, `acuario`, `piscis`) VALUES
(29, '2022-03-24', 'Hoy será un día ideal para dar el siguiente paso hacia una meta importante. Confía en tus capacidades y deja que tus acciones hablen por ti.', 'La paciencia y la prudencia te ayudarán a resolver una situación que parecía complicada. Mantén una actitud positiva y todo fluirá a tu favor.', 'Una noticia inesperada despertará tu entusiasmo. Aprovecha este momento para compartir tus ideas y fortalecer tus relaciones personales.', 'Las emociones estarán de tu lado y te permitirán comprender mejor a quienes te rodean. Un gesto sincero traerá paz y armonía a tu día.', 'Tu determinación será clave para alcanzar un objetivo que llevas tiempo persiguiendo. No permitas que las dudas frenen tu entusiasmo.', 'La organización marcará la diferencia en tus actividades. Resolverás asuntos pendientes con mayor facilidad si mantienes el enfoque en tus prioridades.', 'Será una jornada favorable para recuperar el equilibrio y fortalecer la comunicación con las personas importantes en tu vida. Escuchar será tan valioso como hablar.', 'Tu intuición estará especialmente acertada frente a una decisión importante. Analiza cada alternativa con calma antes de actuar y obtendrás buenos resultados.', 'El optimismo te llevará a descubrir nuevas oportunidades. Una experiencia diferente ampliará tu perspectiva y te dejará una valiosa enseñanza.', 'Los frutos de tu esfuerzo comenzarán a hacerse evidentes. Continúa trabajando con disciplina y no permitas que la impaciencia afecte tus planes.', 'Tu creatividad será la protagonista del día. Una idea innovadora podría convertirse en el inicio de un proyecto lleno de posibilidades.', 'La tranquilidad llegará cuando decidas confiar más en el proceso de la vida. Dedica un momento para reflexionar sobre tus logros y valorar todo lo que has avanzado.'),
(30, '2022-03-30', 'Hoy será una jornada favorable para dejar atrás las dudas y avanzar con mayor confianza. Tu esfuerzo comenzará a reflejarse en resultados positivos.', 'La estabilidad que buscas estará más cerca de lo que imaginas. Mantén la paciencia y no permitas que las preocupaciones afecten tu tranquilidad.', 'Tu facilidad para relacionarte con los demás abrirá nuevas oportunidades. Una conversación inesperada podría marcar el inicio de un proyecto interesante.', 'Las emociones estarán en equilibrio y encontrarás apoyo en una persona de confianza. Aprovecha el día para fortalecer los vínculos familiares.', 'Tu entusiasmo será la clave para superar un reto importante. Mantén una actitud positiva y no temas asumir nuevas responsabilidades.', 'La organización y el compromiso te permitirán resolver asuntos pendientes con éxito. No descuides los pequeños detalles, pues marcarán la diferencia.', 'La armonía llegará al actuar con serenidad frente a una situación inesperada. Escuchar diferentes opiniones te ayudará a tomar una mejor decisión.', 'Tu intuición será una gran aliada para descubrir oportunidades que otros no perciben. Confía en tus instintos, pero actúa siempre con prudencia.', 'Una nueva experiencia despertará tu deseo de crecer y aprender. Mantén la mente abierta, ya que el cambio traerá beneficios para tu futuro.', 'La constancia y la disciplina seguirán acercándote a tus objetivos. No permitas que la impaciencia te haga abandonar un camino que va por buen rumbo.', 'Tu creatividad destacará en una actividad importante. Compartir tus ideas con quienes te rodean abrirá puertas hacia nuevos proyectos.', 'Será un excelente día para renovar tus energías y mirar el futuro con optimismo. La tranquilidad que encuentres hoy fortalecerá tu confianza para los próximos días.'),
(31, '2022-03-31', 'El cierre de este mes traerá la oportunidad de comenzar una nueva etapa con mayor confianza. Aprovecha la experiencia adquirida y continúa avanzando sin temor.', 'La paciencia y la dedicación demostrarán que todo esfuerzo tiene su recompensa. Mantén una actitud serena y evita preocuparte por aquello que no depende de ti.', 'Una noticia positiva renovará tu entusiasmo y despertará nuevas ideas. Comparte tus proyectos con personas de confianza y escucha sus sugerencias.', 'Las emociones estarán en armonía y encontrarás motivos para sonreír. Un momento especial junto a tus seres queridos fortalecerá los lazos que más valoras.', 'Tu determinación será reconocida por quienes han seguido de cerca tu esfuerzo. Es un excelente día para fijarte nuevas metas y mirar el futuro con optimismo.', 'La organización y la disciplina seguirán siendo tus mejores aliadas. Resolverás un asunto pendiente que te permitirá iniciar el próximo mes con mayor tranquilidad.', 'La armonía llegará gracias a una conversación sincera. Mostrar comprensión y respeto fortalecerá una relación importante en tu vida.', 'Tu intuición te ayudará a tomar una decisión que marcará un cambio positivo. Actúa con prudencia y confía en todo lo que has aprendido durante este camino.', 'El optimismo abrirá nuevas posibilidades para tu crecimiento personal. No tengas miedo de aceptar los cambios, pues traerán experiencias enriquecedoras.', 'Los resultados de tu constancia comenzarán a hacerse más evidentes. Sigue trabajando con responsabilidad y mantén la confianza en tus capacidades.', 'Tu creatividad será una fuente de inspiración para quienes te rodean. Una idea diferente podría convertirse en el inicio de un proyecto exitoso.', 'Será un día ideal para agradecer lo vivido durante este mes y prepararte para nuevos desafíos. La serenidad y la esperanza iluminarán el camino que está por comenzar.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pronostico_mensual`
--

CREATE TABLE `pronostico_mensual` (
  `id` int(11) NOT NULL,
  `signo` varchar(20) NOT NULL,
  `enero` varchar(300) NOT NULL,
  `febrero` varchar(300) NOT NULL,
  `marzo` varchar(300) NOT NULL,
  `abril` varchar(300) NOT NULL,
  `mayo` varchar(300) NOT NULL,
  `junio` varchar(300) NOT NULL,
  `julio` varchar(300) NOT NULL,
  `agosto` varchar(300) NOT NULL,
  `septiembre` varchar(300) NOT NULL,
  `octubre` varchar(300) NOT NULL,
  `noviembre` varchar(300) NOT NULL,
  `diciembre` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `pronostico_mensual`
--

INSERT INTO `pronostico_mensual` (`id`, `signo`, `enero`, `febrero`, `marzo`, `abril`, `mayo`, `junio`, `julio`, `agosto`, `septiembre`, `octubre`, `noviembre`, `diciembre`) VALUES
(1, 'aries', 'Amor: El amor se probara con vinculos cercanos a ti. Ten cuidado con lo que haces.\nDinero: Habra algo de prosperidad en tu hogar\nSalud: Tu salud será benefica para este mes', 'Amor: Tu media naranja se encuentra cerca de ti, pero no te das cuenta, fijate en verdad a quien tienes al lado\r\nDinero: Vendrán tiempos dificiles para ti que te tomaran a prueba y debes superar\r\nSalud: Tu salud no resultara afectada este mes', 'Amor: Vendran sucesos dificiles que tienes que afrontar, se consciente en todo lo que haces, ya que puedes herir a alguien cercano a ti.\r\nDinero: Vendra prosperidad para ti\r\nSalud: Pues tener buena salud, sin embargo, ten cuidado con lo que comes', 'Amor: Se superaran todos los acontecimientos dificiles con tus vinculos cercanos, pero ten cuidado en esta etapa\nDinero: Debes ser más precavido con lo que gastas y consumes, ya que esto se vera reflejado en tu estado financiero\nSalud: Tu salud se mantendrá estable sin embargo, ten cuidado ', 'Amor: Tu estado emocional con tu circulo social mejorara, persevera en lo que buscas y quieres obtener\r\nDinero: Vendran dias prosperos y dias dificiles\r\nSalud: Tendras una salud buena si haces lo posible por cuidar de ella', 'Amor: El amor para este mes sera benefico, encontraras verdaderamente la persona que realmente te aprecia\r\nDinero: habra prosperidad para ti y tus allegados\r\nSalud: tu salud se mantendra estable', 'Amor: el amor se vera reflejado en ti, mejorara tu autestima\r\nDinero: Para este mes afrontaras tiempos dificiles, sin embargo, los superaras adecuadamente\r\nSalud: La salud estara un poco afectada, por lo que debes cuidar de ella', 'Amor: Afrontaras situaciones emocionales, trata de manejar de la mejor manera lo que dices y haces\r\nDinero: Tu situacion financiera se mantendra estable\r\nSalud: Tu salud se encontrara sana', 'Amor: El amor te pondra a prueba este mes\r\nDinero: Grandes oportunidades vendran a ti, que te beneficiaran economicamente\r\nSalud: Tu salud sera buena pero debes esforzarte en mejorarla', 'Amor: Para este mes veras las verdaderas personas que te aprecian y acompañan en las buenas y en las malas\r\nDinero: tu situacion financiera se vera un poco dificil, se perseverante en lo que buscas\r\nSalud: come bien este mes, veras los resultados', 'Amor: se presentaran algunos problemas con tu circulo social, trata de remediarlos de la mejor forma\r\nDinero: habra tiempos dificiles y tiempos abundantes\r\nSalud: Tu salud se vera un poco gastada, debes descansar', 'Amor: el amor se presentara mas en esta epoca de reunion y reconciliacion\r\nDinero: Vendran tiempos buenos y productivos\r\nSalud: Cuida de tu salud, mas que todo en lo que comes'),
(2, 'tauro', 'Amor: veras el amor reflejado en ti\r\nDinero: Tu situacion sera precaria\r\nSalud: tendras buena salud', 'Amor: Sin Amor\r\nDinero: Muy poco dinero\r\nSalud: convaleciente', 'Amor: encontraras una persona especial en ti\r\nDinero: La prosperidad llegara\r\nSalud: buena salud', 'Amor: Te llenaras de amor\r\nDinero: No te endeudes\r\nSalud: salud sana', 'Amor: No encontraras buenas personas\r\nDinero: Algo de dinero este mes\r\nSalud: Salud estable', 'Amor: Buen amor\r\nDinero: Necesitaras dinero\r\nSalud: ten cuidado con los accidentes', 'Amor: Tendras problemas familiares que afrontar\r\nDinero: Te pediran prestado tus allegados sin devolucion\r\nSalud: Perfecta salud', 'Amor: Mejor amor\r\nDinero: La abundancia llegara solo si tomas buenas decisiones\r\nSalud: Mejorara tu salud', 'Amor: Algo de amor\r\nDinero: Encontraras un buen trabajo\r\nSalud: Trata de comer sano y veras los resultados', 'Amor: Maravilloso amor\r\nDinero: La prosperidad vendra si tomas el camino correcto\r\nSalud: Algo de buena salud', 'Amor: Perfecto amor\r\nDinero: Te buscaran por interes\r\nSalud: Tu salud sera benefica', 'Amor: Reencontraras amores tanto familiares como propios perdidos\r\nDinero: Te endeudaras y pediras prestamos\r\nSalud: Evita comer comida no saludable');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL,
  `usuario` varchar(50) NOT NULL,
  `contrasena` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`id`, `usuario`, `contrasena`) VALUES
(1, 'luisa', 'luisa123'),
(2, 'oscar', 'oscar123');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `pronostico_anual`
--
ALTER TABLE `pronostico_anual`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `pronostico_diario`
--
ALTER TABLE `pronostico_diario`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `pronostico_mensual`
--
ALTER TABLE `pronostico_mensual`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
